### ISSUE TITLE
Empty wallet and exceptions in log

### ISSUE THREAD

**Issue by olenagerasimova** [zold-io/wts.zold.io#41] opened 2018-07-07 07:44 UTC
Here is what happened:
1. 0crat sent me 7.36 ZLD yesterday in 13:03 GMT+3 after my order was finished (I was not registered in zold jet)
2. I went to wts.zold.io and registered successfully, wallet was empty, on pull there was updating warning
> We are updating your wallet right now. Please, refresh the page in a minute.  
3. I logged in several minutes ago: wallet is still empty, updating warning still there along with a lot of exceptions in log
![image](https://user-images.githubusercontent.com/14931449/42408196-5d370a24-81d1-11e8-9b79-30b5287cb54d.png)
[olenagerasimova_zold.log](https://github.com/zold-io/wts.zold.io/files/2172544/olenagerasimova_zold.log)

So, the main problem here is that I have not got any ZLD: there should be 7.36 from 0crat and bonus for registration. 
And there is also a question: is it ok that 0crat sent me any ZLD? I also received dollars as usual...

**Comment by 0crat** [comment] 2018-07-07 07:44
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-07-07 07:44
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CB28FH2NR) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment] 2018-07-07 22:45
@olenagerasimova this is a duplicate of #40 We don't inform you correctly about the situation now. Try to login in a few hours. You should see your payments.

**Closed by yegor256** 2018-07-07 22:45 UTC

**Comment by 0crat** [comment] 2018-07-07 23:05
The job is not in WBS, won't close the order

**Comment by 0crat** [comment] 2018-07-07 23:05
Job `gh:zold-io/wts.zold.io#41` is not assigned, can't get performer
